'use strict';
const $=id=>document.getElementById(id);
fetch('analysis.json').then(r=>{if(!r.ok)throw Error('No saved analysis');return r.json();}).then(d=>loadAnalysis(d)).catch(()=>{});
const places={kotri_barrage:[25.44238,68.31601,17],sukkur_barrage:[27.67998,68.84556,16],guddu_barrage:[28.41885,69.7129,16],sindh:[26.1,68.5,7],manchar:[26.43,67.67,11],sukkur:[27.69,68.85,12],hyderabad:[25.39,68.36,12],delta:[24.15,67.57,10],karachi:[24.86,67.02,11]};
let boundary,analysis,mode='reference',overlay,googleMap,googleOverlay,googleReady=false;
const map=L.map('map',{zoomControl:false,minZoom:6,maxZoom:20,maxBounds:[[22,65],[30,72]],maxBoundsViscosity:.8}).setView([26.1,68.5],7);
L.control.zoom({position:'topright'}).addTo(map);
L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Tiles © Esri — Source: Esri, Maxar, Earthstar Geographics, and the GIS User Community',maxZoom:19}).addTo(map).on('tileerror',()=>notice('Reference tiles could not load','Check your connection or connect Google satellite.'));
fetch('sindh.geojson').then(r=>{if(!r.ok)throw Error('Boundary unavailable');return r.json()}).then(data=>{boundary=data;L.geoJSON(data,{style:{color:'#e0eac0',weight:1.7,fillColor:'#d9ecad',fillOpacity:.025}}).addTo(map);fit();}).catch(e=>notice('Province outline unavailable',e.message));
Object.entries(places).filter(([k])=>k!=='sindh'&&!k.endsWith('_barrage')).forEach(([k,v])=>L.circleMarker(v,{radius:3,color:'#f5f5da',fillColor:'#fff',fillOpacity:1,weight:1}).addTo(map).bindTooltip(k==='manchar'?'Manchar Lake':k==='delta'?'Indus Delta':k[0].toUpperCase()+k.slice(1),{direction:'right'}));
function notice(title,text){const el=$('notice');el.replaceChildren();const icon=document.createElement('span');icon.className='notice-icon';icon.textContent='i';const box=document.createElement('div'),a=document.createElement('strong'),b=document.createElement('span');a.textContent=title;b.textContent=text;box.append(a,b);el.append(icon,box);}
function fit(){if(googleReady){googleMap.fitBounds({south:23.4,west:66.65,north:28.6,east:71.2});}else if(boundary){map.fitBounds(L.geoJSON(boundary).getBounds(),{padding:[25,50]});}}
function navigate(place){if(!places[place])throw Error('Unknown Sindh location');$('location').value=place;if(place==='sindh')fit();else{const [lat,lng,zoom]=places[place];if(googleReady){googleMap.setCenter({lat,lng});googleMap.setZoom(zoom);}else map.setView([lat,lng],zoom);}return{location:place};}
function openConnections(){$('connectionDialog').showModal();}
['connect','refresh'].forEach(id=>$(id).onclick=openConnections);
$('methodButton').onclick=()=>$('methodDialog').showModal();$('fit').onclick=fit;$('location').onchange=e=>navigate(e.target.value);
function setMode(next){if(!['reference','water','reconstruction'].includes(next))throw Error('Invalid map mode');if(next!=='reference'&&!analysis){openConnections();return{mode,requiresAnalysis:true};}mode=next;document.querySelectorAll('.layer').forEach(el=>el.classList.toggle('active',el.dataset.mode===mode));$('mapMode').textContent={reference:'Satellite reference',water:'Detected water',reconstruction:'Synthetic reconstruction'}[mode];renderLayer();return{mode};}
document.querySelectorAll('.layer').forEach(el=>el.onclick=()=>setMode(el.dataset.mode));
const ProtectedTiles = L.GridLayer.extend({createTile(coords, done){return StructureMask.tile(this.options.url,coords,document,done);}});
let structuresReady=false;
fetch('structures.geojson').then(r=>{if(!r.ok)throw Error('Structure data unavailable');return r.json();}).then(d=>{StructureMask.setData(d);structuresReady=true;$('structureStatus').textContent=d.features.length.toLocaleString()+' mapped structure features preserved. Footprints are approximate; unmapped structures may still be covered.';renderLayer();}).catch(()=>{$('structureStatus').textContent='Structure protection unavailable. Reload to retry.';});
function renderLayer(){
 if(overlay){map.removeLayer(overlay);overlay=null;}if(googleReady)googleMap.overlayMapTypes.clear();googleOverlay=null;
 const layer=analysis?.layers[mode];
 if(mode!=='reference'&&layer){
  const opacity=Number($('opacity').value)/100;
  if(googleReady){
   const tiles=new Set();googleOverlay={tileSize:new google.maps.Size(256,256),maxZoom:20,getTile(coord,z,doc){const canvas=StructureMask.tile(layer.url,{x:coord.x,y:coord.y,z},doc,err=>{if(err)notice('Analysis tiles unavailable or expired','Rerun the processor and load a fresh analysis file.');});canvas.style.opacity=this.opacity;tiles.add(canvas);return canvas;},releaseTile(tile){tiles.delete(tile);},opacity,setOpacity(value){this.opacity=value;tiles.forEach(t=>t.style.opacity=value);}};googleMap.overlayMapTypes.push(googleOverlay);
  }else{overlay=new ProtectedTiles({url:layer.url,opacity,maxZoom:20,attribution:'Contains modified Copernicus Sentinel data / Google Earth Engine; structure masks © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}).addTo(map);overlay.on('tileerror',()=>notice('Analysis tiles unavailable or expired','Rerun the processor and load a fresh analysis file.'));}
  notice(mode==='water'?'Experimental water classification':'Synthetic surface · not a current photograph',mode==='water'?`${analysis.method} · Mapped structures excluded from display; totals use raw satellite classification.`:'Satellite detail retained on land and mapped structures. Dry patches remain lower resolution.');
 }else notice('Reference imagery · not a live water map',googleReady?'Google satellite imagery. Dates vary by location.':'Esri World Imagery. Connect Google Maps to use Google satellite.');
}
function tileURL(url,x,y,z){return url.replace('{x}',x).replace('{y}',y).replace('{z}',z);}
$('opacity').oninput=e=>{$('opacityValue').textContent=e.target.value+'%';overlay?.setOpacity(Number(e.target.value)/100);googleOverlay?.setOpacity(Number(e.target.value)/100);};
function validateAnalysis(d){if(d?.schemaVersion!==1||d.region!=='Sindh')throw Error('Use a Sindh analysis produced by the included processor.');if(!['Sentinel-2 MNDWI','Sentinel-1 VV threshold'].includes(d.method))throw Error('Unrecognized analysis method.');for(const k of ['water','reconstruction']){const url=d.layers?.[k]?.url;if(typeof url!=='string'||!['{x}','{y}','{z}'].every(p=>url.includes(p)))throw Error('Missing '+k+' map tiles.');const u=new URL(url);if(u.protocol!=='https:'||u.hostname!=='earthengine.googleapis.com')throw Error('Only HTTPS Earth Engine tile URLs are accepted.');}for(const k of ['windowStart','windowEnd','latestScene','generatedAt'])if(typeof d[k]!=='string'||!Number.isFinite(Date.parse(d[k])))throw Error('Invalid '+k);for(const k of ['waterKm2','coveragePercent'])if(!Number.isFinite(d[k])||d[k]<0)throw Error('Invalid analysis statistics.');if(d.coveragePercent>100||d.waterKm2>200000)throw Error('Analysis statistics out of range.');return d;}
function loadAnalysis(d){analysis=validateAnalysis(d);$('dateValue').textContent=new Date(d.latestScene).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});$('dateDetail').textContent=`Window: ${d.windowStart.slice(0,10)} – ${d.windowEnd.slice(0,10)}`;$('waterValue').textContent=d.waterKm2.toLocaleString('en',{maximumFractionDigits:0})+' km²';$('waterDetail').textContent=d.method+' · experimental';$('coverageValue').textContent=d.coveragePercent.toFixed(1)+'%';$('legendWater').textContent='Detected water';$('refresh').firstChild.textContent='Update analysis ';$('connectionDialog').close();setMode('water');}
$('analysisFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1_000_000)throw Error('Analysis file is too large.');loadAnalysis(JSON.parse(await file.text()));$('connectionError').textContent='';}catch(err){$('connectionError').textContent=err.message;}finally{e.target.value='';}};
$('googleConnect').onclick=()=>{const key=$('googleKey').value.trim();if(!key){$('connectionError').textContent='Enter a restricted Google Maps browser key.';return;}if(googleReady){$('connectionError').textContent='Google satellite is already connected.';return;}$('googleConnect').disabled=true;window.gm_authFailure=()=>{$('connectionError').textContent='Google rejected the key. Check API enablement, billing and website restrictions. Reload to retry.';$('googleMap').hidden=true;$('map').hidden=false;googleReady=false;};window.initSindhGoogle=()=>{googleMap=new google.maps.Map($('googleMap'),{center:{lat:26.1,lng:68.5},zoom:7,mapTypeId:'satellite',streetViewControl:false,mapTypeControl:false,fullscreenControl:false,restriction:{latLngBounds:{north:30,south:22,west:65,east:72},strictBounds:false}});if(boundary){googleMap.data.addGeoJson(boundary);googleMap.data.setStyle({strokeColor:'#e0eac0',strokeWeight:2,fillOpacity:.025});}googleReady=true;$('map').hidden=true;$('googleMap').hidden=false;$('googleKey').value='';$('connectionDialog').close();fit();renderLayer();};const script=document.createElement('script');script.src='https://maps.googleapis.com/maps/api/js?key='+encodeURIComponent(key)+'&callback=initSindhGoogle&loading=async';script.async=true;script.onerror=()=>{$('connectionError').textContent='Google Maps could not load. Check your connection and reload to retry.';};document.head.append(script);};
if(document.modelContext?.registerTool){for(const tool of [{name:'navigate_sindh',description:'Navigate to a named location in Sindh.',inputSchema:{type:'object',properties:{location:{type:'string',enum:Object.keys(places)}},required:['location'],additionalProperties:false},execute:({location})=>navigate(location)},{name:'set_sindh_layer',description:'Select reference, observed water or reconstructed surface. Opens connection setup if analysis is absent.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['reference','water','reconstruction']}},required:['mode'],additionalProperties:false},execute:({mode})=>setMode(mode)}]){try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}})).catch(()=>{});}catch{}}}

