'use strict';
const processorURL='https://ee-rawal-karim23.projects.earthengine.app/view/sindh-water-observatory';
let selectedBox=null,selectionLayer=null,selectionGoogle=null,drawing=false,firstCorner=null,searchMarker=null,searchAt=0;
const searchCache=new Map(),historicalAnalyses=new Map();
function localToday(){const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10);}
$('historyDate').max=localToday();$('historyDate').value=$('historyDate').max;
function inRing(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function inSindh(lon,lat){if(!boundary)return false;return boundary.features.some(f=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return polys.some(r=>inRing([lon,lat],r[0])&&!r.slice(1).some(h=>inRing([lon,lat],h)));});}
function boxArea(b){return 6371**2*Math.abs((b[2]-b[0])*Math.PI/180*(Math.sin(b[3]*Math.PI/180)-Math.sin(b[1]*Math.PI/180)));}
function updateProcessorLink(){const d=$('historyDate').value,ok=selectedBox&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&$('historyDate').checkValidity()&&d>='2020-01-01'&&d<=$('historyDate').max;$('processDate').setAttribute('aria-disabled',String(!ok));if(ok)$('processDate').href=processorURL+'#'+'history=true;auto=true;date='+encodeURIComponent(d)+';box='+encodeURIComponent(JSON.stringify(selectedBox))+';';else $('processDate').removeAttribute('href');}
function missingForProcessor(){const d=$('historyDate');if(!d.value||!d.checkValidity())return 'Choose a date between 2020-01-01 and '+d.max+'.';if(!selectedBox)return 'Draw an area on the map first. The date is sent to Earth Engine together with the area.';return '';}
$('historyDate').onchange=()=>{updateProcessorLink();const missing=missingForProcessor();$('historyStatus').textContent=missing||('Date '+$('historyDate').value+' ready. Use “Find clear days & export” to process it in Earth Engine. The map shows '+(analysis?.observationMode==='single-clear-day'?analysis.latestScene:'the saved multi-day snapshot')+' until you load the result.');};
$('processDate').onclick=e=>{const missing=missingForProcessor();if(missing){e.preventDefault();$('historyStatus').textContent=missing;}};
let previewLayer=null,previewGoogle=null;
function clearPreview(){if(previewLayer){map.removeLayer(previewLayer);previewLayer=null;}if(previewGoogle){previewGoogle.setMap(null);previewGoogle=null;}}
function cornerBox(lat,lng){return[Math.min(lng,firstCorner[0]),Math.min(lat,firstCorner[1]),Math.max(lng,firstCorner[0]),Math.max(lat,firstCorner[1])];}
function previewTo(lat,lng){if(!drawing||!firstCorner)return;const b=cornerBox(lat,lng),km2=boxArea(b),ok=km2<=400,color=ok?'#ffda76':'#ff6b5b';if(googleReady){const bounds={west:b[0],south:b[1],east:b[2],north:b[3]};if(!previewGoogle)previewGoogle=new google.maps.Rectangle({map:googleMap,clickable:false,strokeWeight:2,fillOpacity:.08});previewGoogle.setOptions({bounds,strokeColor:color,fillColor:color});}else{const bounds=[[b[1],b[0]],[b[3],b[2]]];if(!previewLayer)previewLayer=L.rectangle(bounds,{interactive:false,weight:2,dashArray:'6 4',fillOpacity:.08}).addTo(map);previewLayer.setBounds(bounds).setStyle({color});}$('areaStatus').textContent=(km2<10?km2.toFixed(2):Math.round(km2).toLocaleString())+' km²'+(ok?' · release or click to finish.':' · larger than 400 km²: the map will zoom into it so you can draw again.');}
function stopDrawing(){drawing=false;firstCorner=null;clearPreview();map.getContainer().classList.remove('drawing-map');map.doubleClickZoom.enable();map.dragging.enable();pointerStart=null;if(googleReady)googleMap.setOptions({draggableCursor:null,disableDoubleClickZoom:false,draggable:true});$('drawArea').textContent='Draw area';}
function chooseCorner(lat,lng){if(!drawing)return;if(!firstCorner){firstCorner=[lng,lat];$('areaStatus').textContent='Now click the opposite corner.';return;}const b=cornerBox(lat,lng),km2=boxArea(b);firstCorner=null;clearPreview();if(km2<.001){$('areaStatus').textContent='That area is too small. Drag a larger rectangle.';return;}if(km2>400){if(googleReady)googleMap.fitBounds({west:b[0],south:b[1],east:b[2],north:b[3]});else map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{animate:false});$('areaStatus').textContent=Math.round(km2).toLocaleString()+' km² is over the 400 km² limit. Zoomed in: now drag a smaller rectangle.';return;}const points=[[b[0],b[1]],[b[0],b[3]],[b[2],b[1]],[b[2],b[3]],[(b[0]+b[2])/2,(b[1]+b[3])/2]];if(!points.some(p=>inSindh(...p))){$('areaStatus').textContent='Select an area within Sindh. Border areas will be clipped to the province.';return;}stopDrawing();selectedBox=b;if(selectionLayer)map.removeLayer(selectionLayer);if(selectionGoogle)selectionGoogle.setMap(null);selectionLayer=L.rectangle([[b[1],b[0]],[b[3],b[2]]],{interactive:false,color:'#ffda76',weight:2,fillOpacity:.08}).addTo(map);if(googleReady)selectionGoogle=new google.maps.Rectangle({map:googleMap,bounds:{west:b[0],south:b[1],east:b[2],north:b[3]},strokeColor:'#ffda76',fillOpacity:.08,clickable:false});$('areaStatus').textContent=boxArea(b).toFixed(2)+' km² selected. Analysis is clipped to Sindh.';$('exportArea').disabled=false;updateProcessorLink();$('historyStatus').textContent=missingForProcessor()||'Area and date '+$('historyDate').value+' ready. Use “Find clear days & export”.';}
let pointerStart=null;const mapBox=map.getContainer();
function onPress(x,y,lat,lng){if(!drawing)return;pointerStart={x,y};if(!firstCorner){firstCorner=[lng,lat];pointerStart.fresh=true;$('areaStatus').textContent='Drag to the opposite corner, or release and click it.';}}
function onRelease(x,y,lat,lng){if(!drawing||!pointerStart)return;const moved=Math.hypot(x-pointerStart.x,y-pointerStart.y)>6,fresh=pointerStart.fresh;pointerStart=null;if(moved||!fresh)chooseCorner(lat,lng);}
mapBox.addEventListener('pointerdown',e=>{if(!drawing||e.button>0||e.target.closest('.leaflet-control'))return;const ll=map.mouseEventToLatLng(e);onPress(e.clientX,e.clientY,ll.lat,ll.lng);});
mapBox.addEventListener('pointermove',e=>{if(!drawing)return;const ll=map.mouseEventToLatLng(e);previewTo(ll.lat,ll.lng);});
window.addEventListener('pointerup',e=>{if(!drawing||!pointerStart||googleReady)return;const ll=map.mouseEventToLatLng(e);onRelease(e.clientX,e.clientY,ll.lat,ll.lng);});
let googleClickMap=null;
$('drawArea').onclick=()=>{if(!boundary){$('areaStatus').textContent='Wait for the province boundary to load.';return;}if(drawing){stopDrawing();$('areaStatus').textContent='Drawing cancelled.';return;}if(googleReady&&googleClickMap!==googleMap){const xy=e=>e.domEvent?[e.domEvent.clientX??e.domEvent.changedTouches?.[0]?.clientX,e.domEvent.clientY??e.domEvent.changedTouches?.[0]?.clientY]:[0,0];googleMap.addListener('mousedown',e=>onPress(...xy(e),e.latLng.lat(),e.latLng.lng()));googleMap.addListener('mouseup',e=>onRelease(...xy(e),e.latLng.lat(),e.latLng.lng()));googleMap.addListener('mousemove',e=>previewTo(e.latLng.lat(),e.latLng.lng()));googleClickMap=googleMap;}drawing=true;firstCorner=null;map.getContainer().classList.add('drawing-map');map.doubleClickZoom.disable();map.dragging.disable();if(googleReady)googleMap.setOptions({draggableCursor:'crosshair',disableDoubleClickZoom:true,draggable:false});$('drawArea').textContent='Cancel drawing';const zoom=googleReady?googleMap.getZoom():map.getZoom();$('areaStatus').textContent='Drag a rectangle on the map (or click two corners). Zoom with the wheel or +/−.'+(zoom<10?' Areas are limited to 400 km²; a larger box zooms the map in so you can refine it.':'');};
$('clearArea').onclick=()=>{stopDrawing();selectedBox=null;if(selectionLayer)map.removeLayer(selectionLayer);if(selectionGoogle)selectionGoogle.setMap(null);$('areaStatus').textContent='Click Draw area to select a rectangle.';$('exportArea').disabled=true;updateProcessorLink();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawing){stopDrawing();$('areaStatus').textContent='Drawing cancelled.';}});
function saveJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportArea').onclick=()=>{if(!selectedBox)return;const [w,s,e,n]=selectedBox;saveJSON({type:'FeatureCollection',features:[{type:'Feature',properties:{kind:'requested_area',requested_date:$('historyDate').value,note:'Selection rectangle only, not water classification. Processor clips this area to Sindh.'},geometry:{type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]}}]},'sindh-selected-area.geojson');};
$('loadHistory').onclick=openConnections;
const originalLoadAnalysis=loadAnalysis;
loadAnalysis=function(d){if(d.observationMode==='single-clear-day'&&(!Array.isArray(d.area)||d.area.length!==4||!d.area.every(Number.isFinite)||d.area[0]>=d.area[2]||d.area[1]>=d.area[3]||d.area[0]<66.5||d.area[2]>71.3||d.area[1]<23.6||d.area[3]>28.7))throw Error('Historical analysis has invalid area bounds.');originalLoadAnalysis(d);if(d.observationMode==='single-clear-day'){const [w,s,e,n]=d.area;if(googleReady)googleMap.fitBounds({west:w,south:s,east:e,north:n});else map.fitBounds([[s,w],[n,e]],{padding:[30,30],maxZoom:17});$('waterValue').textContent=d.waterKm2.toLocaleString('en',{maximumFractionDigits:3})+' km²';historicalAnalyses.set(d.latestScene+'|'+JSON.stringify(d.area),d);$('historyStatus').textContent='Displayed: '+d.latestScene+' · cloud-screened single day for its analysis area.';$('loadedHistory').replaceChildren();for(const value of historicalAnalyses.values()){const b=document.createElement('button');b.textContent=value.latestScene;b.onclick=()=>loadAnalysis(value);$('loadedHistory').append(b);}}else $('historyStatus').textContent='Displayed: multi-day snapshot '+d.windowStart+' to '+d.windowEnd+'.';};
$('searchForm').onsubmit=async e=>{e.preventDefault();const q=$('placeQuery').value.trim();if(q.length<2||$('searchSubmit').disabled)return;if(!boundary){$('searchResults').textContent='Province boundary is loading. Try again shortly.';return;}$('searchSubmit').disabled=true;$('searchResults').textContent='Searching…';const wait=1100-(Date.now()-searchAt);if(wait>0)await new Promise(r=>setTimeout(r,wait));searchAt=Date.now();try{let results=searchCache.get(q.toLowerCase());if(!results){const params=new URLSearchParams({q,format:'jsonv2',countrycodes:'pk',viewbox:'66.6,28.6,71.2,23.7',bounded:'1',limit:'10'});const response=await fetch('https://nominatim.openstreetmap.org/search?'+params,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Search is temporarily unavailable. Please try later.');results=(await response.json()).filter(r=>inSindh(Number(r.lon),Number(r.lat)));searchCache.set(q.toLowerCase(),results);}$('searchResults').replaceChildren();if(!results.length)$('searchResults').textContent='No matching location within Sindh. Try another spelling or nearby town.';for(const r of results){const b=document.createElement('button');b.type='button';b.textContent=r.display_name;b.onclick=()=>{const lat=Number(r.lat),lng=Number(r.lon);if(searchMarker){if(searchMarker.setMap)searchMarker.setMap(null);else map.removeLayer(searchMarker);}if(googleReady){googleMap.setCenter({lat,lng});googleMap.setZoom(15);searchMarker=new google.maps.Marker({map:googleMap,position:{lat,lng},title:r.display_name});}else{map.setView([lat,lng],15);searchMarker=L.marker([lat,lng]).addTo(map);searchMarker.bindTooltip(r.display_name);}$('searchResults').replaceChildren();$('placeQuery').value=r.name||r.display_name.split(',')[0];};$('searchResults').append(b);}const credit=document.createElement('a');credit.href='https://www.openstreetmap.org/copyright';credit.textContent='Search © OpenStreetMap contributors';credit.target='_blank';credit.rel='noopener';$('searchResults').append(credit);}catch(err){$('searchResults').textContent=err.message;}finally{$('searchSubmit').disabled=false;}};

const originalRenderLayer=renderLayer;renderLayer=function(){originalRenderLayer();$('mapMode').textContent={reference:'Satellite reference',water:'Detected water',reconstruction:'Synthetic reconstruction'}[mode];if(mode!=='reference'&&analysis?.observationMode==='single-clear-day')$('mapMode').textContent+=' · '+analysis.latestScene+' · selected area';};
// The Earth Engine app's "Show result on Sindh map" button returns here as #analysis=<encodeURIComponent(JSON)>.
function loadFromLink(){if(!location.hash.startsWith('#analysis='))return false;try{loadAnalysis(JSON.parse(decodeURIComponent(location.hash.slice(10))));}catch(err){$('historyPanel').open=true;$('historyStatus').textContent='The result link could not be loaded: '+err.message+' Rerun the day in Earth Engine.';}return true;}
loadFromLink();window.addEventListener('hashchange',loadFromLink);
