'use strict';
const processorURL='https://ee-rawal-karim23.projects.earthengine.app/view/sindh-water-observatory';
let selectedBox=null,selectionLayer=null,selectionGoogle=null,drawing=false,firstCorner=null,searchMarker=null,searchAt=0;
const searchCache=new Map(),historicalAnalyses=new Map();
$('historyDate').max=new Date().toISOString().slice(0,10);$('historyDate').value=$('historyDate').max;
function inRing(point,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const a=ring[i],b=ring[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])inside=!inside;}return inside;}
function inSindh(lon,lat){if(!boundary)return false;return boundary.features.some(f=>{const polys=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;return polys.some(r=>inRing([lon,lat],r[0])&&!r.slice(1).some(h=>inRing([lon,lat],h)));});}
function boxArea(b){return 6371**2*Math.abs((b[2]-b[0])*Math.PI/180*(Math.sin(b[3]*Math.PI/180)-Math.sin(b[1]*Math.PI/180)));}
function updateProcessorLink(){const d=$('historyDate').value,ok=selectedBox&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&$('historyDate').checkValidity()&&d>='2020-01-01'&&d<=$('historyDate').max;$('processDate').setAttribute('aria-disabled',String(!ok));if(ok)$('processDate').href=processorURL+'#'+'history=true;date='+encodeURIComponent(d)+';box='+encodeURIComponent(JSON.stringify(selectedBox))+';';else $('processDate').removeAttribute('href');}
$('historyDate').onchange=()=>{updateProcessorLink();$('historyStatus').textContent='Requested date changed. The displayed map is still '+(analysis?.observationMode==='single-clear-day'?analysis.latestScene:'the saved multi-day snapshot')+'.';};
function stopDrawing(){drawing=false;firstCorner=null;map.getContainer().style.cursor='';$('drawArea').textContent='Draw area';}
function chooseCorner(lat,lng){if(!drawing)return;if(!firstCorner){firstCorner=[lng,lat];$('areaStatus').textContent='Now click the opposite corner.';return;}const b=[Math.min(lng,firstCorner[0]),Math.min(lat,firstCorner[1]),Math.max(lng,firstCorner[0]),Math.max(lat,firstCorner[1])];stopDrawing();if(boxArea(b)<.001||boxArea(b)>400){$('areaStatus').textContent='Select an area between 0.001 and 400 km². Zoom in and try again.';return;}const points=[[b[0],b[1]],[b[0],b[3]],[b[2],b[1]],[b[2],b[3]],[(b[0]+b[2])/2,(b[1]+b[3])/2]];if(!points.some(p=>inSindh(...p))){$('areaStatus').textContent='Select an area within Sindh. Border areas will be clipped to the province.';return;}selectedBox=b;if(selectionLayer)map.removeLayer(selectionLayer);if(selectionGoogle)selectionGoogle.setMap(null);selectionLayer=L.rectangle([[b[1],b[0]],[b[3],b[2]]],{color:'#ffda76',weight:2,fillOpacity:.08}).addTo(map);if(googleReady)selectionGoogle=new google.maps.Rectangle({map:googleMap,bounds:{west:b[0],south:b[1],east:b[2],north:b[3]},strokeColor:'#ffda76',fillOpacity:.08,clickable:false});$('areaStatus').textContent=boxArea(b).toFixed(2)+' km² selected. Analysis is clipped to Sindh.';$('exportArea').disabled=false;updateProcessorLink();}
map.on('click',e=>chooseCorner(e.latlng.lat,e.latlng.lng));
let googleClickMap=null;
$('drawArea').onclick=()=>{if(!boundary){$('areaStatus').textContent='Wait for the province boundary to load.';return;}if(drawing){stopDrawing();$('areaStatus').textContent='Drawing cancelled.';return;}if(googleReady&&googleClickMap!==googleMap){googleMap.addListener('click',e=>chooseCorner(e.latLng.lat(),e.latLng.lng()));googleClickMap=googleMap;}drawing=true;firstCorner=null;map.getContainer().style.cursor='crosshair';$('drawArea').textContent='Cancel drawing';$('areaStatus').textContent='Click the first corner on the map.';};
$('clearArea').onclick=()=>{stopDrawing();selectedBox=null;if(selectionLayer)map.removeLayer(selectionLayer);if(selectionGoogle)selectionGoogle.setMap(null);$('areaStatus').textContent='Click Draw area to select a rectangle.';$('exportArea').disabled=true;updateProcessorLink();};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drawing){stopDrawing();$('areaStatus').textContent='Drawing cancelled.';}});
function saveJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('exportArea').onclick=()=>{if(!selectedBox)return;const [w,s,e,n]=selectedBox;saveJSON({type:'FeatureCollection',features:[{type:'Feature',properties:{kind:'requested_area',requested_date:$('historyDate').value,note:'Selection rectangle only, not water classification. Processor clips this area to Sindh.'},geometry:{type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]}}]},'sindh-selected-area.geojson');};
$('loadHistory').onclick=openConnections;
const originalLoadAnalysis=loadAnalysis;
loadAnalysis=function(d){originalLoadAnalysis(d);if(d.observationMode==='single-clear-day'){historicalAnalyses.set(d.latestScene+'|'+JSON.stringify(d.area),d);$('historyStatus').textContent='Displayed: '+d.latestScene+' · cloud-screened single day for its analysis area.';$('loadedHistory').replaceChildren();for(const value of historicalAnalyses.values()){const b=document.createElement('button');b.textContent=value.latestScene;b.onclick=()=>loadAnalysis(value);$('loadedHistory').append(b);}}else $('historyStatus').textContent='Displayed: multi-day snapshot '+d.windowStart+' to '+d.windowEnd+'.';};
$('searchForm').onsubmit=async e=>{e.preventDefault();const q=$('placeQuery').value.trim();if(q.length<2)return;if(!boundary){$('searchResults').textContent='Province boundary is loading. Try again shortly.';return;}if(Date.now()-searchAt<1100)return;searchAt=Date.now();$('searchSubmit').disabled=true;$('searchResults').textContent='Searching…';try{let results=searchCache.get(q.toLowerCase());if(!results){const params=new URLSearchParams({q,format:'jsonv2',countrycodes:'pk',viewbox:'66.6,28.6,71.2,23.7',bounded:'1',limit:'10'});const response=await fetch('https://nominatim.openstreetmap.org/search?'+params,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Search is temporarily unavailable. Please try later.');results=(await response.json()).filter(r=>inSindh(Number(r.lon),Number(r.lat)));searchCache.set(q.toLowerCase(),results);}$('searchResults').replaceChildren();if(!results.length)$('searchResults').textContent='No matching location within Sindh. Try another spelling or nearby town.';for(const r of results){const b=document.createElement('button');b.type='button';b.textContent=r.display_name;b.onclick=()=>{const lat=Number(r.lat),lng=Number(r.lon);if(googleReady){googleMap.setCenter({lat,lng});googleMap.setZoom(15);}else{map.setView([lat,lng],15);if(searchMarker)map.removeLayer(searchMarker);searchMarker=L.marker([lat,lng]).addTo(map);searchMarker.bindTooltip(r.display_name);}$('searchResults').replaceChildren();$('placeQuery').value=r.name||r.display_name.split(',')[0];};$('searchResults').append(b);}const credit=document.createElement('a');credit.href='https://www.openstreetmap.org/copyright';credit.textContent='Search © OpenStreetMap contributors';credit.target='_blank';credit.rel='noopener';$('searchResults').append(credit);}catch(err){$('searchResults').textContent=err.message;}finally{$('searchSubmit').disabled=false;}};

const originalRenderLayer=renderLayer;renderLayer=function(){originalRenderLayer();$('mapMode').textContent={reference:'Satellite reference',water:'Detected water',reconstruction:'Synthetic reconstruction'}[mode];if(mode!=='reference'&&analysis?.observationMode==='single-clear-day')$('mapMode').textContent+=' · '+analysis.latestScene+' · selected area';};
